### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Ystartff** [risc-mi/braintumor-ddpm#1]
Hello! Is your dataset the original brain2021 dataset and not processed?

**Comment by aalshenoudy** [comment]
Hello!

As mentioned in the README.md, we use the Brain Tumor Segmentation (BraTS) 2021 dataset. The publicly available training data is used to create our 2D subset, which we use in all of our experiments.

We are adding a few tutorial notebooks to the documentation that should be public quite soon.
